apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cfk-source
  namespace: ${releaseNamespace}
spec:
  interval: 6h
  url: oci://packages.confluent.io/helm/confluent-for-kubernetes
  ref:
    tag: 3.2.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: confluent-operator
